### ISSUE TITLE
Negative food decay results in double minus

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#103]
![image](https://user-images.githubusercontent.com/1611537/31043974-a15ba0f8-a5c6-11e7-8f71-e7161d4c299d.png)

![image](https://user-images.githubusercontent.com/1611537/31043976-abd3ec0c-a5c6-11e7-8905-b7712b8ecaff.png)

**Comment by guilhermeportela** [comment]
May I work on this issue, @WaveHack?

**Comment by WaveHack** [comment]
Sure thing.

Here are my thoughts on the issue:

Food shouldn't go below 0. If during a tick (`artisan game:tick`) food goes below 0, it should be set to 0 and the difference (if any) should be converted to casualties due to starvation (another issue, but both could be combined). If there's no difference (i.e. food is already 0), the full amount so go into casualties.

This is one of the very few formulas I'm not very sure on what needs to happen exactly.

Each unit (peasant, draftee, every military unit) eats 0.25 food every tick (hour). So for every point of negative food during a tick, 2 to 4 units should die. Preferably evenly spread out over all the different unit types a dominion has.

**Comment by guilhermeportela** [comment]
Understood, @WaveHack.

**Comment by WaveHack** [comment]
Alright sweet. Let me know if you have any questions. 😃

**Comment by guilhermeportela** [comment]
Where do I determine whether a unit is dead or not?

**Comment by WaveHack** [comment]
Yeah units are stored as integers (amount of units) on dominions.unit_*. If some of them die, just subtract some numbers.

To check if some should die, just put a check for negative food in TickCommand@tickDominionResources for now after the getFoodNetChange call.

I want to move the amount (and types) of casualties somewhere in the PopulationCalculator, but I need to think about how I want that. So feel free to think of something or just throw it in the tick class and I'll refactor it sometime later.

**Comment by WaveHack** [comment]
I just checked with someone and apparently the amount of casualties should be split 50/50 between peasants and military units. Between military units it should be split (I guess) evenly between the military units you have.

So for example, if you have:

- 1000 peasants
- 150 SD (specialist defensive, i.e. military_unit2)
- 25 spies
- 25 wizards

And during a game:tick you have a shortage of 50 food, means 50*4 = 200 casualties.

First 100 casualties go to peasants (= 900 remaining peasants).
Second 100 casualties are split betwene SD, spies and wizard. Each take 33 casualties (either be generous with the rounding or have one of those 3 take 34, I don't really mind either scenario).

**Comment by WaveHack** [comment]
Oh btw @guilhermeportela I realize this issue might be a bit bigger than it seemed. Mainly because the issue is related to another issue.

If you feel like skipping it or picking up another issue instead, that's totally fine too. 👍

**Comment by guilhermeportela** [comment]
That's no problem at all, @WaveHack. It was pretty easy to understand the code, and I should be opening a PR any time soon. Just checking for possible caveats that we may have not foreseen.
