### ISSUE TITLE
Reset password functionality

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#117]
Long overdue

**Comment by WaveHack** [comment]
Sure, feel free to leave a PR!

Please try to leverage [Laravel's password reset functionality](https://laravel.com/docs/5.5/passwords) as much as possible.

**Comment by WaveHack** [comment]
Heya @MJBrennan, had any luck on this issue? Or are you preoccupied with other stuff? Which is totally fine, so I can assign it to someone else interested in it.

**Comment by MJBrennan** [comment]
Hey really sorry I started on it but got distracted by other things. You
can reassign this issue. If I have any small bugs that need addressing I
could have a look at them in the near future

**Comment by WaveHack** [comment]
Done. Thanks for the PR!
