### ISSUE TITLE
Add --open flag to artisan round:start

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#119]
### Expected Behavior
*Explain desired behavior for bugs and feature requests*
I want to be able to create a round which opens for registrations right away from the CLI. A `--open` flag on the round:start Artisan command would suffice.

The round should open 'today midnight', start in '+3 days midnight' (instead of '+5 days midnight') and end in '+53 days midnight' (instead of '+55 days midnight').

### Current Behavior
*What is the current situation and/or output for bugs?*
When running `php bin/artisan round:start`, the round always opens in two days (and starts in five).

**Comment by Braunson** [comment]
I can do this.

**Comment by WaveHack** [comment]
Sweet! Let me know if you have any questions or such.
