### ISSUE TITLE
Change specialist unit training times from 12hr to 9hr

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#146]
### Expected Behavior
Military specialist units should take only 9 hours to train, instead of 12 hours.

All other units (elite, spies and mages) should still take 12 hours to train.

### Current Behavior
All units take 12 hours to train currently.

### Context
Specialist units are the fields 'military_unit1' and 'military_unit2' on the dominions table. This is the same for every race. (fyi units 3 and 4 are elite units, but that's out of the scope for this issue).

Code change should probs go in the TrainActionService class.

**Comment by danielsouzaaf** [comment]
Working on this issue!
