### ISSUE TITLE
Add land rezoning

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#15]
https://dominion.lykanthropos.com/www.kamikazegames.com/dominion/scribes/rezone.htm

https://github.com/WaveHack/OpenDominion/blob/resources/domsim/screenshots/Screenshot_13.png

Here is how land rezoning worked in the original Dominion

Should go in its own controller: `OpenDominion\Http\Controllers\Dominion\RezoneController` with the corresponding `RezoneActionService`

Just take a look at how construction and/or exploration is done and try to keep it consistent with that

Note on working with land and buildings: If a dominion has 100 land_plain and 10 buildings constructed on plains, then that dominion has only 90 plain barren land. Most of the calculations and stuff are already in `LandCalculator`

So re-zoning land only works for barren land, not total land (including buildings constructed on the latter)

`LandCalculator->getBarrenLandByLandType()` should help you with that on both GET and passing it to the view, and on POST to verify you don't convert more (or less) than what you have. Feel free to implement the UI as you see fit

Re-zoning has a cost of platinum (per acre of land converted), equal to `round((($dominion->totalLand - 250) * 0.6) + 250)`

**Comment by Kender2** [comment]
Fixed in PR #74
