### ISSUE TITLE
Resource selection should stay the same after investing in improvements

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#150]
### Current Behavior
When you invest a resource other than with gems on the improvements page and click the 'Invest' button, it POSTs to itself and then redirects to GET of itself (i.e. /dominions/improvements) and the resource selection reverts back to gems.

### Expected Behavior
Resource selection should stay the same after you click 'Invest'. If you navigate away and back to improvements, it can default to gems instead.

The 'resource' input var should be passed from the POST to to the GET route and used in the view to select the proper resource in the select list, if it's set (i.e. only if you POSTed aka clicked 'Improve' on the previous request).

**Comment by pjonckiere** [comment]
I'll make a PR for this shortly.
