### ISSUE TITLE
Discussion about invasions

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#151]
Alright folks, discussion / note-to-self thread.

I want to bring up the topic about invasions and how they worked in Dominion. Notably the numbers (or at least realistic estimates) on how things were calculated.

Question: Anyone know if there was any mechanic in place that prevented or discouraged you from invading and black ops'ing realmies?

Afaik there wasn't, but would like some confirmation on this. And if not, do you reckon there should be something in place? Perhaps like a warning message or just flat-out forbid it?

I'm trying to work out some numbers with regards to invasions. I have the following in mind, based on reading the scribes, a half complete wiki and digging through the round win stories:

Some terminology first for those unfamiliar:
- Raw OP: Offensive Power, the attack stat of your units summed together
- Raw DP: Defensive Power, the defense stat of your units summed together
- Modded OP/DP: Raw OP/DP but with multiplier bonus gained from things like Gyphon Nest/Guard Tower buildings, Forges/Walls improvements or many other factors
- Successful invasion: You send more modded OP than they have modded DP at home. Just 1 point of additional OP is enough. No RNG.
- Bounce: Unsuccessful invasion. I.e. you didn't send enough OP to break their DP
- Raze: Bounce by 15% or less difference in your OP vs their DP
- EG range: Elite Guard range, anyone (with their land size) within 75-133% of your land size
- Prestige: Stat giving 1% max population, OP and food production per 100 prestige. Gained by successfully invading others.

**Land grab amount**: Successful invasion grabs 5% of target dominion's total land, split 50/50 between barren and constructed/constructing (destroying any buildings or constructing buildings in the process), and either 1) spread evenly across all land types or 2) spread in a ratio that the target has (i.e. if the target has 60% plains / 20% forest / 20% water, you gain that ratio of the 5% land grab)? In addition, you get 50% bonus land (discovered) on a successful invasion, possibly only if a dominion has been hit X times in the last 24 hours.

**Prestige gain** for attacker: Successfully attacking in EG range gives prestige equal to 5% of target's prestige + 20, maxed at 10% of your own prestige +20. Not accounting for war status, taking wonders or tech ruleset modifiers. Also this gets reduced probably by depending on how much the target has been hit in the last 24 hours, see 'defensive casualties' below.

Someone on the forum mentioned that the prestige gain could be 20% of the land grab (not counting bonus land). Prestige page on the wiki mentions the above 5% based on target prestige. But the wiki on the web archive has been known of being out of date sometimes.

**Prestige loss**: Razing, being successfully invaded (on the wiki it says 5% prestige loss), receiving black ops during a mutual war (tiny amounts) or hitting dominions smaller than 66%. I need to work on the exact numbers for this.

**Offensive casualties**: 8.5% needed to break the target or just 8.5% of what you send if you don't send enough, either spread evenly across all unit types or based on ratio. Doubled casualties (8.5% x2 = 17%) on a raze (defined as: modded OP is at least 15% lower than target's modded DP).(edited)
Defensive casualties: Around ~6.6% (as defined on the wiki) scaled by relative landsize (i.e. range). So say 100% range = 6.6%, 75% range say 6.6% * .75 = 4.95%?. Also depending on how many times you've been hit the past 24 hours, it scales further from 100% - 80% - 60% - 55% - 45% - 35%. Spread out between all units that help defend (i.e. have DP), either flat spread or again, based on unit ratios you have. Oversending apparently causes more defensive casualties. And I'd assume undersending reduces defensive casualties too.

**Also, to verify:**
- To initiate an invasion you must have at least 70% morale
- Boats carry 30 troops each for units that don't swim/fly
- You must leave at least 33% worth of DP based on the OP you send at home (e.g. if you send 1000 OP, you have to leave at least 333 DP at home)
- You may not send more than 125% of modded OP relative to your modded DP at home per invasion (eg if you have 1000 DP, you may not send more than 1250 OP at a time)
- "Non-unit casualty bonuses are summoned together then capped at 80%. Unity casualty bonuses are applied to this number (except gnomish suicide squads)" <-- need to think out how this would work

**Needs verification:**
- Sending invasions lower morale. Any clues on numbers for this? Any modifiers for razes, bounces or successful invasions?
- Lower morale means lower DP. Any clue about the scaling? (scribes invade page; "Keep in mind, however, that as your morale goes down, your defense does not battle as hard.")
- Successful invasions also lower morale of target dominion (wiki round 4 win story; "We took him to 0% morale, ...")

Consider the following scenario where multiple grabs from different people in a span of an hour seem to increase in size:

round-74.html:539: 11:00:32 AM Victorious on the battlefield, Russian roulette (# 16) conquered 335 land from This is My Ninja Way (# 23).
round-74.html:540: 11:59:29 AM Victorious on the battlefield, slow.internet.guy (# 16) conquered 340 land from This is My Ninja Way (# 23).
round-74.html:541: 12:00:00 PM Victorious on the battlefield, Mucho Badasstico (# 16) conquered 382 land from This is My Ninja Way (# 23).

My guess on this is because it's multiple people with different land sizes so the target is a different relative % landsize (i.e. range), like 75% range=grab then 85% then 100% or something. Same-dominion invasions right after each other do reduce land grabs, further proving this theory. Also this means that land grab % is not reduced by the 'recently invaded protection bonus', reducing 100% - 80% - 60% etc. Only defensive casualties, possibly prestige loss and possibly spell damage or damaging spy ops too.

I don't necessarily want to do it 100% perfectly right the first time before I release invasions, but I want to have a good start based on the data we have.

Anyone who wants to give some input on this (especially veteran Dominon players) is encouraged to do so.

**Comment by blackreign** [comment]
Not sure where you got the 5% land grab from. When I played it was always around 10% (from target land), depending on the ['target land' / 'your land'] ratio. In the calculation tab on the excel sim I tried to approximate the formula but never got the exact one.

The percentage seems to fit nicely around 3000 acres of land. 

MIN(0,15; 0,25 * ( 0,7 - EXP( -1,3 * 'Target land' / 'Attacker land' ) ))*1,1

**Comment by WaveHack** [comment]
Ah thanks for that. I thought I read somewhere it was 5%. I'll try to see if I can find the source for it somewhere.

**Comment by blackreign** [comment]
You're welcome. Also, I remember people leaving barren land as a buffer zone, because barren land would get grabbed before constructed buildings.

**Comment by WaveHack** [comment]
Ah useful to know! This is exactly the kind of info I need. If you have more, please do share. 😄

**Comment by blackreign** [comment]
Only thing i can say is that the 10% is right. Not sure about the invasion morale penatly. Gut feeling says between 3% and 10% depending on land ratio. Also not sure about morale gain per tick, maybe it was 6% per tick. Target morale... again not sure.

There was also a halfling spy operation called demoralise, to prevent someone from attacking, or lowering his defense.

**Comment by ImSparticus** [comment]
5% (and increasing below EG range) morale drop sounds too high. A fairly common (though dubious) strategy was to hit low-acre targets on land DP a bunch of times for 12 acres a pop. A 10% drop at minimum range would cap you at 4 hits!

**Comment by WaveHack** [comment]
Can we assume it's just 5% flat morale drop per (successful) invasion, regardless of range?

**Comment by blackreign** [comment]
Good enough for me atm

**Comment by WaveHack** [comment]
Errata: Morale drop for yourself after invading someone will be -5% at 75% targets and up, linearly scaling down to -10% at 40% targets (lower end of NG range).

NG range isn't implemented yet; everyone uses EG range. So it's more of a thing for the future once I implement guards.

**Comment by WaveHack** [comment]
bump

Needs doublechecking if I've got everything

**Comment by WaveHack** [comment]
I think I got everything! Closing issue
