### ISSUE TITLE
Fix unit training return message

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#156]
### Current Behavior
When training one wizard, for example, the message reads: "Training of 1 wizards begun at a cost of 500 platinum, 0 ore, 1 draftee and 0 wizards."

### Expected Behavior
The message needs to be rewritten to make sense.

In this case, it must be "Training of 1 wizard begun at a cost of 500 platinum and 1 draftee".

When training 50x Archer and 50x Spearman, it should read: "Training of 50 archers and 50 spearmen begun at a cost of X platinum, Y ore and 100 draftees.

### Context
- Message gets built in TrainActionService.
- Sentence needs to be constructed so it makes sense and omits 0-values.
- Also need str_plural() on unit names, draftee cost and wizard cost (if any).
- Remember to use number_format() around all the numbers.

**Comment by soueuls** [comment]
I will happily take on this, I love hacktoberfest, it made me want to contribute to open source, and now I am just enjoying it 👍 

Anyway, I will set up the environment locally and tackle this.
