### ISSUE TITLE
Receiving application encryption error on running dev server

### ISSUE THREAD

**Issue by mmartinsky** [WaveHack/OpenDominion#159]
### Current Behavior
*(What is the current situation and/or output for bugs?)*

1. Clone Repo
2. composer install
3. Run init script
4. php bin/artisan serve

### Expected Behavior
*(Explain desired behavior for bugs and feature requests)*
Should start development server and produce home page on browser navigation to http://localhost:8000

### Steps to Reproduce
*(For bugs, describe the steps you took to reliably reproduce the issue. For feature requests, either omit this section or describe step by step how your feature should work.)*
Received Laravel error regarding application encryption

### Environment
*(For bugs, on what environment are you running? Production, development or your own local setup?)*

### Context
*(Anything else you want me to know. Useful info include the version hash at the bottom right of OpenDominion and server software versions (like PHP) if you're running on your local machine. For feature requests, try to include some motivation.)*

**Comment by WaveHack** [comment]
Thanks for the report. I'll take a look at it.

**Comment by WaveHack** [comment]
Weird. Just tested it and it shouldn't happen.

Thanks for the PR regardless. I'll leave it in the contributing doc, just in case. :+1:
