### ISSUE TITLE
Look into tick duration

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#175]
Goals:

- Reduce amount of queries that run during hourly tick

Suggestions:

- Grouping doms to update by race, and load only race+unit+perk data once for each block of identical races - OR - load all the races/units in memory, instead of always fetching race+units+perks for each dom
- Doing two passes of updates. First one a transaction on active players (users.last_activity >= 3 days, or something), then another transaction right after on all the other (inactive) players.
- Optimizing queues to use less queries (there's a PR open for that atm)
- Optimizing queues to have 1 single query update ALL the queues for every dominion (in active round)

**Comment by WaveHack** [comment]
#528

**Comment by internetfett** [comment]
The new PR is #635
