### ISSUE TITLE
Day counter is broken

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#186]
### Current Behavior
*(What is the current situation and/or output for bugs?)*
`Day 0/50, hour 14. Version: r1498 @ local (develop #2933120)`

### Expected Behavior
*(Explain desired behavior for bugs and feature requests)*
Should be day 30 ish? Dashboard says round is ending in 21 days.

**Comment by Kirbstomper** [comment]
Adding start and end dates to where this bug is seen and you can change in your local instance to match 

start_date:  2017-11-29 00:00:00
end_date: 2018-01-18 00:00:00
