### ISSUE TITLE
Refactor prestige formula

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#209]
https://github.com/WaveHack/OpenDominion/blob/92b0a36e7b8c1c387a759ffe6b39ccd900355335/src/Calculators/Dominion/ProductionCalculator.php#L201-L202

Can be refactored to `($dominion->prestige / 10000)`.

Needs to be refactored in all relevant places (max pop, food production and OP).

**Comment by blackreign** [comment]
current implementation:
raw * multiplier

possible refactor
raw * bonuses * prestige bonus
where bonuses is e.g. 100%+10%+5%
and prestige bonus is e.g. 102,5%

**Comment by blackreign** [comment]
Yeah that works too, and requires less changes. :-)
