### ISSUE TITLE
Refactor {{ csrf_field() }} to @csrf

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#223]
For you, @Hodgy :)

**Comment by Hodgy** [comment]
Thanks :D

**Comment by WaveHack** [comment]
Seems like I can't assign the issue after all. Oh well

**Comment by Hodgy** [comment]
I think you can only assign to people who are part of the repo

**Comment by WaveHack** [comment]
Yeah I believe so too.
