### ISSUE TITLE
Rework protection

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#225]
A topic that has been brought up by the veteran community.

Protection is often seen as a clunky mechanic, and an alternative to protection was proposed: scripting protection.

The idea is to not have any in-game protection, but instead having a sim script the first 72 hours based on desired input, and have the round instantly start from there. Ideally creating a sim would happen during the pre-round to have time doing it.

One concern I brought up was regarding newer and inexperienced players. My suggestion is to have some sort of template system where with a few generic templates (based on race) for certain playstyles (exploring or attacking) and/or being able to share your own sim as a template for others, possibly with a community voting system.

Registering during a round could either use the template system and/or the protection like it is currently.

Another option would be having players choose if they want to sim with a basic template and start with a higher building/land count, or go the regular 3-day protection route for more refined and sophisticated protection strategy. Templates probably need to be tweaked then to probably be something simpeler than a full-fledged Excel sim, where you can tweak every parameter every hour, to balance things.

Arguments:

- Beneficial for newer players. More instant interaction and less 'what the fuck am I waiting for'

Mixed arguments:

- Protection as a waiting period is a good time to getting to know realmies, sorting out monarchy, making general plans etc. Although this could also happen when there's no protection and the game starts instantly.

Counter-arguments:

- It's a significant change of how Dominion worked. At least early-game.

**Comment by ImSparticus** [comment]
I would lean toward the version that keeps 3 real days of protection. This is a turn-off for new players, but lots of things about Dominion are a turn-off for new players.

Either way, some form of protection simming is sorely needed. The extreme dedication required to get even decent results repels veterans and new players alike. For the remaining 47 days, you could theoretically login every 8 hours and be mostly fine. Such a laid back approach is disastrous in protection. Even casual explorers need to be hardcore for this period, or they'll fall way behind.

Creating sims is fun and rewards skill. For many players, these were carefully guarded secrets. But actually executing them is miserable and unhealthy. The insane practice of 1:55ing was born from this.

**Comment by stromblom** [comment]
Make it scriptable. Have 12h or something before the beginning of the round so people still have time to get to know each other.

And having predefined builds should be easy. And as suggested the community could share their sims for the round.

**Comment by WaveHack** [comment]
Placing this in the icebox until later
