### ISSUE TITLE
Fix Valhalla

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#237]
### Current Behavior
Networth is off if you compare a player in Strongest Dominions vs Strongest Humans/Nomads.

For example, in Beta Round 5 on Valhalla, see dominion Half. Strongest Dominions shows him with 399,235 NW, on Stronest Humans it's suddenly 1,740,458 NW.

### Expected Behavior
Needs fixing!

**Comment by rearley** [comment]
Was reviewing the latest example on the beta server and everything looks good. Is this still an issue?

**Comment by WaveHack** [comment]
Ah yes, thanks for bringing this up. I believe this was fixed a little while ago with #346.
