### ISSUE TITLE
Exploring draftee/acre cost discussion

### ISSUE THREAD

**Issue by blackreign** [WaveHack/OpenDominion#245]
Somewhere between the rounds, explore cost went up 10%. This however causes a bump in the draftee/acre cost growth.
It used to be 4 draftees until 299 acres, then 5 draftees until 419 acres, then 6 until 632.. and so on.
Now it is 4 draftees until 299, then *bam* 6 draftees until 508.

For me, I have never experienced the new formula in old dominion. But the change probably was necesary because of the lower playerbase making attacking harder.

Still, I think we can reduce the draftee cost to the old value (i.e. remove the 10%). What do you think?

**Comment by WaveHack** [comment]
For reference, this is the current draftee/acre cost by land size thresholds:

Land 250: 4 draftees
Land 300: 6 draftees
Land 509: 7 draftees
Land 699: 8 draftees
Land 883: 9 draftees
Land 1062: 10 draftees
Land 1239: 11 draftees
Land 1413: 12 draftees
Land 1586: 13 draftees
Land 1756: 14 draftees
Land 1926: 15 draftees

Discussed on Discord to leave as-is. At the end of DC the draftee costs were raised to (likely) incentivize attacking.
