### ISSUE TITLE
Super awesome

### ISSUE THREAD

**Issue by idontdodev** [WaveHack/OpenDominion#253]
Hi guys, 
I just wanted to say thanks for undertaking this project. I have been playing this game a lot back in the day and I cant count the times I thought back to it. I was sad to see it discontinued and I am very happy to see you guys pulling your resources together to get this done.

Just needed that said.

Kind regards, 
NiQuil

**Comment by WaveHack** [comment]
Hey NiQuil,

Thank you! I - together with help of a handful of wonderful contributors - have been working hard the past few years rebuilding and improving Dominion.

We have a community chat going at Discord (looks a bit like IRC, but more modern) with quite some people from back then. If you want, feel free to join and chat, regardless if you play the new game or not. 😃 

The Discord can be found here: https://discordapp.com/invite/mFk2wZT

WaveHack

**Comment by idontdodev** [comment]
Nnice, I'll join tonight when I get back from work.
~NiQuil
