### ISSUE TITLE
Trying to visit a non-existing page ends with Internal Server Error

### ISSUE THREAD

**Issue by krzysztof-sikorski** [WaveHack/OpenDominion#271]
### Current Behavior

If you manually eding URL field and remove a part or add some garbage, then upon visiting such URL you get and Internal Server Error.

### Expected Behavior

Visiting URL of non-existing page ends with a "page not found" message instead of server error.

### Steps to Reproduce

Visit one of following URLs:
- https://beta.opendominion.net/qwerty
- https://beta.opendominion.net/dominion/advisors/qwerty
- https://beta.opendominion.net/dominion/construct/qwerty

### Environment

Official beta instance, version: r1783 @ (develop #fb9b148)

### Context

Encouraged by previous issue I went to check which other pages may react badly to "hacking" their URLs.

**Comment by Sylk** [comment]
@WaveHack close this.

**Comment by WaveHack** [comment]
Ah yes, thanks!
