### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by wumix** [WaveHack/OpenDominion#272]
I usw Composer how ti installiert it with composer?

**Comment by WaveHack** [comment]
OpenDominion is a PHP project, and not a PHP package installable through Composer.

To get it working on your local machine, please consult [CONTRIBUTING.md](https://github.com/WaveHack/OpenDominion/blob/develop/CONTRIBUTING.md#local-development).

**Comment by wumix** [comment]
Thank you
