### ISSUE TITLE
Add support for packs

### ISSUE THREAD

**Issue by stromblom** [WaveHack/OpenDominion#280]
Current idea:

- Any amount of doms with the same race.
- Alignment needs to be same.
- Max number of doms in a pack will depend on the size of the realms.
- Min number of doms in a pack should be 2.
- On creation of a pack you will choose a password, which can be shared to let people join.

Currently working in: https://github.com/stromblom/OpenDominion/tree/feature/packs

**Comment by stromblom** [comment]
Currently working in: https://github.com/stromblom/OpenDominion/tree/feature/packs

**Comment by WaveHack** [comment]
Done
