### ISSUE TITLE
Put important warning alerts on status page (or all pages)

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#340]
Things like starvation, invasions etc

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#feedback`.

**Comment by stromblom** [comment]
I think a rework of how notifications are displayed would solve this.

**Comment by internetfett** [comment]
Fixed by #615
