### ISSUE TITLE
Move draftees to bottom on release units page table

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#341]
_No content_

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#feedback`.

**Comment by stromblom** [comment]
BR mentioned this b/c he almost released his AMs. But moving draftees could make people release specs instead of draftees.

**Comment by WaveHack** [comment]
It's a beta. Things are bound to change. I'd rather take that chance to replicate the UX of dominion as much as possible.

If needed I can add it to the next announcement post.

**Comment by stromblom** [comment]
The current ordering is more logical than draftees being at the bottom.

**Comment by WaveHack** [comment]
You're right. Leaving it as is
