### ISSUE TITLE
Invasions - Cap prestige on incoming

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#359]
Prestige can not be higher than current land (including inc land this hour).

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@slz` in `#development`.

**Comment by stromblom** [comment]
Also on land loss, we need to make sure that prestige not exceeds land.

**Comment by WaveHack** [comment]
What do you mean? If your land gets stolen, your prestige gets lowered automatically (on top of the prestige stolen) to match your new total land size as a max?

**Comment by blackreign** [comment]
For normal players and strategies this will not happen. This cap will prevent prestige farming around 250 acres (not that i'm convinced this is a viable strategy).
Perhaps OOP targets will be affected by this, if they lose more than 5% land on hits.

**Comment by stromblom** [comment]
True. It is much more complicated to implement than it is worth. So skip for now?

**Comment by WaveHack** [comment]
Fine by me
