### ISSUE TITLE
Figure out what to do on failed spy ops with lizardfolk chameleons

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#413]
On failing a spy op with having only chams, no chams get killed.

On failing a spy op and having some spies and also chams, only spies get killed, not chams either.

Need to figure out what to do with this.

**Comment by WaveHack** [comment]
Apparently chams never suffer casualties on info ops, but they may/should on black ops?

**Comment by internetfett** [comment]
They now DIE!
