### ISSUE TITLE
Invasion result page grabs live recently invaded count for target

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#430]
Need to be set in the invasionResult data array

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by WaveHack** [comment]
Note to self: Pick up with prio

**Comment by internetfett** [comment]
Fixed via 895242c
