### ISSUE TITLE
Don't kill spies on failed info ops when your total spies is below 100 (to 200)

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#445]
_No content_

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by stromblom** [comment]
Just change the ceil to a floor and it should solve all the problems.

**Comment by WaveHack** [comment]
Cool, thanks for the input!

**Comment by stromblom** [comment]
Perhaps we should tweak the percentage also

**Comment by WaveHack** [comment]
What do you suggest?

**Comment by Dr-Eki** [comment]
From Discord discussion: 0.1% for info-ops (and a note to make it some higher for black-ops in the future).
