### ISSUE TITLE
DP bug / Firewalker Phoenix has 4.5 dp

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#462]
Need to check for rounding issues in the code, as well in the UI

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by internetfett** [comment]
I noticed this when implementing Dark Elf. The UI uses number_format, which ends up rounding the unit OP/DP values. I wrapped it with a quick and dirty conditional to either round it to one or no decimal places.
Didn't look into anything further than that, though.

**Comment by WaveHack** [comment]
I think we can just get rid of number_format() for $unit->power_* all together.

**Comment by WaveHack** [comment]
Was just an UI issue, I believe. Closing issue since I think it's now fixed.
