### ISSUE TITLE
Add invasion stats to statistics advisor

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#475]
They're showing 0 atm for successful invasions etc. Can be recalculated from game events table

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by internetfett** [comment]
Already fixed for last round and beyond, not sure we need to reconstruct any past rounds.
