### ISSUE TITLE
Add Clairvoyance spell

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#477]
_No content_

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by stromblom** [comment]
Remember to not add the links to battle reports!

**Comment by WaveHack** [comment]
Thanks!

**Comment by internetfett** [comment]
#532
