### ISSUE TITLE
Stuff for round 13

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#481]
Change server time, downsize realms, downsize packs, limit amount of unique races per pack, and limit packs per realm

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by WaveHack** [comment]
Default realm size has been changed to 6. Default pack size to 3.

**Comment by internetfett** [comment]
Outdated
