### ISSUE TITLE
Doublecheck if invasion calc includes morale mods

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#488]
_No content_

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by stromblom** [comment]
I already checked this, and it seemed perfectly fine to me. But a double check would be nice.

**Comment by WaveHack** [comment]
Yeah OPMultiplier and DPMultiplier in the JS code. Looks correct.
