### ISSUE TITLE
Implement daily bonuses

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#54]
New page: 'Daily Bonus', in the sidebar under Advisors (in the General section).

Just two buttons on that page (and maybe some explanation text).

Platinum Bonus: Instantly gives you platinum equals 4 * peasants
Land Bonus: Instantly gives you 20 acres of land for your race's home land type (e.g. plains for humans)

Both can be taken once a day. Once you take one, the button should be disabled until daily reset. You can still take the other one that day.

It also doesn't matter if you take a bonus at 01:00 or 23:00, both will reset at 00:00 regardless. Except the more peasants you have upon clicking the platinum bonus, the bigger your received platinum bonus will be. (It's recommended to take the plat bonus when you have the most peasants, usually as late in the day as possible. But YMMV if your peasants get assassinated during the day when espionage is implemented etc.)

Both buttons reset for everyone at 00:00 UTC (server time).

Tech details:

- Route could be GET /dominion/bonuses, POST /dominion/bonuses/platinum and POST /dominion/bonuses/land
- Add migration which adds daily_platinum and daily_land (booleans) on the dominions table, default 0/false.
- When you click a button (create DailyBonusActionRequest for validation rules and DailyBonusActionService), set the relevant boolean field it to 1 and award the dominion the platinum or land.
- In the game:tick, check if the current time is 00:00, then reset every dominion's daily_* back to 0.

Bonus points:

- Add some labels (like either [2] for 2 bonuses, [1] for 1 bonus, or preferably [P]latinum and [L]and) to the menu item if you have those bonuses available, so you won't forget it.

Example from the AdminLTE docs:

![image](https://user-images.githubusercontent.com/1611537/31586115-ea8911d6-b1cc-11e7-8704-56d94c1da258.png)

**Comment by pjonckiere** [comment]
I think I've done everything as described in this ticket. 

Remarks:
- In the game tick command I added a check on hour and minutes, but I'm unsure how to test that.
- The merge conflict seems to add two methods in my branch, where I only added one method.

**Comment by WaveHack** [comment]
Thanks you!
