### ISSUE TITLE
Update unit op/dp on military train/release page with land/building perks

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#550]
E.g. sylvan dryad always shows 0/3. Need to take into account offense/defense_per_bulding/land

Probably suffixed with an asterisk to denote it's a dynamic value. E.g. '0/6*'

Also check invade page for op/dp per unit row

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by internetfett** [comment]
Good call, I could probably whip this up pretty fast, but the asterisk would be fine as a quick fix too.

**Comment by WaveHack** [comment]
I think we can use `MilitaryCalculator->getUnitPowerWithPerks()` for this.

Params:
- $selectedDominion ($dominion)
- null ($opposingForceRaceName)
- null ($landRatio)
- $unit (in the loop over $units)
- 'offense'/'defense' ($powerType)

Also please check if it eager loads everything properly, to not end up with +40 db queries on those pages.

**Comment by WaveHack** [comment]
Fixed
