### ISSUE TITLE
404 error when viewing ops in op center

### ISSUE THREAD

**Issue by Mullalove** [WaveHack/OpenDominion#562]
## description 

When trying to view clairvoyance ops either I or other realmies have gained in the ops center user is taken to 404 error screen 

## Expected Behavior
Clairvoyance should be displayed 

## Actual Behavior
404 error displayed 

## Steps to Reproduce

1.go to ops centre 
2.select a clairvoyance eg Url https://beta.opendominion.net/dominion/op-center/clairvoyance/4
3.404 error 
4.

## Your Environment

* OpenDominion version (bottom right in the game):0.6.2-5
* Browser Name and version:mobile chrome v75, android device 
* Operating System and version (desktop or mobile): android version 9

**Comment by internetfett** [comment]
Fixed in #641
