### ISSUE TITLE
OP on Invade page does not include Morale

### ISSUE THREAD

**Issue by Dr-Eki** [WaveHack/OpenDominion#563]
## Description
OP calculation on Invade page does not include Morale. It shows OP as if Morale were 100%.

## Expected Behavior
It should reduce OP if morale is under 100%.

## Actual Behavior
It shows OP as if Morale were 100%.

## Steps to Reproduce
1. Have morale under 100%.
2. Go to Invade page.
3. Calculate/check OP.

**Comment by internetfett** [comment]
Completed in the round-15 branch.
