### ISSUE TITLE
Casualties calculated after land loss

### ISSUE THREAD

**Issue by internetfett** [WaveHack/OpenDominion#566]
This causes a bad interaction with immortal_vs_land_range if the target is hit into a different bracket. Probably other strange things as well.

**Comment by stromblom** [comment]
Should be easy to move that before, no?

**Comment by internetfett** [comment]
I think easiest is to just pass in the 'before' land ratio without recalculating it.

**Comment by stromblom** [comment]
Sounds like a plan.

**Comment by internetfett** [comment]
Nevermind, that range calculation is done all over the place. Changing the order looks fine and also fixes the thing with hobbo casualties before plunder.
