### ISSUE TITLE
Improvement formula is probably off

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#574]
> (1 - exp(-$improvementPoints / ($this->getImprovementCoefficient($improvementType) * $totalLand + 15000)))
> I believe the improvement formulas are incorrect
> The original formulas look like:
> MAX(1-e^(-1POINTS/(7500*LAND+15000)))
> "e" refers to the constant 2.71828....
> but instead of e to the power of (a bunch of stuff) it seems to be 1 to the power of (a bunch of stuff)
> so improvements are greatly deflated

Needs looking into and fixing.

**Comment by internetfett** [comment]
I looked into this a bit today and exp() is definitely raising 'e' to some power.
Raising 1 to some power is always 1 and the whole thing would be 0.

**Comment by WaveHack** [comment]
I believe the person reported this corrected their statement. Improvements should be working as intended.
