### ISSUE TITLE
Hide races on Valhalla in rounds that didn't have doms with said races

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#612]
Not sure how to implement this properly. Maybe a one-time query on hitting a valhalla/round page, then querying the db which races played in that round, then caching those results? And have subsequent pageloads use that array result (containing races) from cache, to not show 'largest spirits/undead/lycan/etc in round 1-13'

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#github`.

**Comment by internetfett** [comment]
Fixed in #713
