### ISSUE TITLE
Spy/Wiz operations formula v3

### ISSUE THREAD

**Issue by stromblom** [WaveHack/OpenDominion#627]
Formula will be changed to be linear
* Info-ops base: 80%.
* Theft base: 50%.
Calculations can be found here:
~~https://docs.google.com/spreadsheets/d/1vvp8f2BxTN3yq3Jf9OzENaOtkZzjanPr-hsAKdEVqE8/edit#gid=0~~
https://github.com/blackreign/Dominion-Simulator/blob/master/ops%20chance.xlsx

Spy ops casualties:
```
[Base] = [Info ops: 0.5 / Theft: 1]
[Spy casualties info ops] = clamp([Base] * [Ratio], 0.5, 2) * [Forest Haven reduction]
```

**Comment by stromblom** [comment]
Formula will be:
`min(Base, Base * Attacker Ratio * 5) * ((1 - Difference / 3) * 1/3 + (Attacker Ratio / Defender Ratio) * 2/3)`

Clamped between 0 and 100%.

**Comment by stromblom** [comment]
Community vote changed formula to:
Info ops:
```
0.8 ^ (2 / (([Attacker Ratio / Defender Ratio] * 1.4) ^ 1.2))
```
Theft:
```
0.8 ^ (2 / (([Attacker Ratio / Defender Ratio] * 1.2) ^ 1.2))
```

**Comment by WaveHack** [comment]
Is this implemented? Can we close this issue?

**Comment by internetfett** [comment]
The theft formula here should have been (has been updated):
```
**0.6** ^ (2 / (([Attacker Ratio / Defender Ratio] * 1.2) ^ 1.2))
```

Black ops formula is implemented as:
```
        $ratioRelative = $selfRatio / $targetRatio;
        $ratioDifference = $selfRatio - $targetRatio;
        $successRate = (
            max(0, (0.08 * $ratioDifference)) +
            ((($ratioRelative ** 0.6) * 0.25) ** 0.6) +
            min(0, (0.05 * $ratioDifference))
        );
```

**Comment by internetfett** [comment]
Added in #763
