### ISSUE TITLE
Fix dominion_history table

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#665]
Currently with the $model->increment/decrement calls it doesn't process any changes, other than peasants_last_hour

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#dev-feedback`.

**Comment by internetfett** [comment]
The tick changes PR makes that stuff work again, but needs something to fix the original problem of action services causing a race condition with the tick.

**Comment by WaveHack** [comment]
Alright cool, thanks for the info!

**Comment by internetfett** [comment]
Fixed by #635
