### ISSUE TITLE
Able to leave royal guard/elite guard 12 Clicks after successful entry into guard

### ISSUE THREAD

**Issue by Mullalove** [WaveHack/OpenDominion#689]
After succesfully entering Royal guard (rg) or elite guard (eg),  user is able to leave the appropriate guard after 12 clicks.

## Description

After succesfully entering Royal guard (rg) or elite guard (eg),  user can leave guard after 12 clicks rather than 48 clicks as per the help text on the page. This introduces ability for users to move in and out of guard quickly to hit targets out of range before moving back into the cover of guard with less risk/consiquence.

## Expected Behavior

After succesfully entering Royal guard (rg) or elite guard (eg),  as per the help text on screen user should not be able to leave the guard for 48 clicks from the click where the guard is succesfully entered.

## Actual Behavior

After succesfully entering Royal guard (rg) or elite guard (eg),  user can leave guard after 12 clicks rather than 48 clicks as per the help text on the page

## Steps to Reproduce

1.apply for RG/EG
2.wait 24 clicks to enter guard
3.wait 12 clicks
4.apply to leave guard

## Your Environment

* OpenDominion version (bottom right in the game):
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by WaveHack** [comment]
Fixed
