### ISSUE TITLE
Fools gold success cast message incorrect 

### ISSUE THREAD

**Issue by Mullalove** [WaveHack/OpenDominion#694]
After casting fools gold successfully, user is given message advising spell will be active for an incorrect period. 

## Description

Casting fools gold successfully means the user is told "Your wizards cast the spell successfully, and it will continue to affect your dominion for the next 12 hours." however the spell only lasts 10 hours. 

## Expected Behavior

Message should advise 
"Your wizards cast the spell successfully, and it will continue to affect your dominion for the next 10 hours."

## Actual Behavior

User is told cast spell will affect their dominion for 12 hours 

## Steps to Reproduce

1.cast fools gold successfully 
2.incorrect messaging provided.
3.
4.

## Your Environment

* OpenDominion version (bottom right in the game):
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by internetfett** [comment]
Added fix to #687
