### ISSUE TITLE
Monarchy

### ISSUE THREAD

**Issue by SrslySirius** [WaveHack/OpenDominion#696]
Add the option to vote for a realmmate on the government page. This should be selectable via dropdown menu. Monarchy is won automatically with a simple plurality. In the event of a tie, largest Dominion wins monarchy. If land size is also equal, whichever Dominion comes first alphabetically is the winner.

**Comment by SrslySirius** [comment]
Monarchs can declare war (when implemented), change the realm name (when implemented), and post announcements to the Status page of realmmates.

**Comment by internetfett** [comment]
Completed in the round-15 branch.
