### ISSUE TITLE
Restrict Excessive Release of Troops

### ISSUE THREAD

**Issue by SrslySirius** [WaveHack/OpenDominion#698]
Currently there are no restrictions in place for releasing troops. Any Dominion can release 100% of all units at any time. As a simplified solution to this problem, I propose a minimum DPA threshold (perhaps 30) beyond which defensive troops can not be released.

**Comment by SrslySirius** [comment]
Actually a dynamic DPA would probably make more sense. Something like 1.7 x DayOfRound

**Comment by internetfett** [comment]
This was set to something like 15% of total defense per 24 hours.
