### ISSUE TITLE
Realm page is broken in new round

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#73]
### Expected Behavior
*Explain desired behavior for bugs and feature requests*

Realm page navigator should show realms in active round only

### Current Behavior
*What is the current situation and/or output for bugs?*

Realm page navigation links to realms in previous (and potential future) round(s)

![image](https://user-images.githubusercontent.com/1611537/27511720-9032a430-592b-11e7-896c-4583225bd472.png)

### Steps to Reproduce
*For bugs, describe the steps you took to reliably reproduce the issue. For feature requests, either omit this section or describe step by step how your feature should work.*

Not tested, but this should be accurate:

1. Start round
2. Register dominion with good race
3. End said round
4. Start new round
5. Register dominion with evil race and select it
6. Goto realm page, click on realm navigation buttons
7. Shows realms from previous round

It's [broken online](https://dev.opendominion.wavehack.net/dominion/realm) in all its glory

### Environment
*For bugs, on what environment are you running? Production, development or your own local setup?*

Online, few commits down the master branch

### Context
*Anything else you want me to know. Useful info include the version hash at the bottom right of OpenDominion and server software versions (like PHP) if you're running on your local machine. For feature requests, try to include some motivation.*

**Comment by mrpudn** [comment]
Hmm, it doesn't look like any of the `game:round-open`, `game:round-start`, or `game:round-end` commands are implemented yet - is that correct?

**Comment by WaveHack** [comment]
There's a makeshift `round:start` command I made a while ago.

https://github.com/WaveHack/OpenDominion/blob/master/src/Console/Commands/RoundStartCommand.php
