### ISSUE TITLE
Form Input Validation

### ISSUE THREAD

**Issue by r00tmebaby** [WaveHack/OpenDominion#747]
I have started playing around 15 but found a very bad issue which just broke my desire to play at the moment. 

There is no proper form field it seems that only on the HTML form but there is no server-side because I can add negative values and override the data. Haven't tested other injections but that was quite enough to report.

Also, consider implementing Recaptcha, email validation is far away from sufficient and do not bet too much on Laravel to do your work as a developer. 

<img>https://i.gyazo.com/b5ce648a9c431329d7ecb5eef0608fe9.png</img>

**Comment by WaveHack** [comment]
We found out about it not long ago and are already working on a fix. But thank you for reporting it. Needless to say we're going to tweak those numbers down a bit.

Recaptcha is on the list of things to look into in the near future. And can you elaborate on your Laravel part? I'm curious.

**Comment by r00tmebaby** [comment]
Great!

**Comment by WaveHack** [comment]
I think this was mostly on us, not properly utilizing Laravel's input validation. We made a fix that does include checking for positive numbers.

If you happen to stumble upon any future bugs or issues, please report them here on the issue tracker again. Thanks again!
