### ISSUE TITLE
Always return array from action service methods

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#90]
Something like:

```PHP
return [
    'message' => 'message to be displayed in the flash alert and source of translations for later',
    'data' => [
        // optional data to return
       'platinumCost' => 50000,
       'moraleDrop' => 100,
    ],
];
```

And on success always show $result['message'] in the flash message in the controller post methods

**Comment by WaveHack** [comment]
Or we could have an ActionServiceResponse class/interface with getMessage()?

**Comment by pjonckiere** [comment]
PR https://github.com/WaveHack/OpenDominion/pull/132
