### ISSUE TITLE
Toggle building help text (or have it on icon hover)

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/OpenDominion#97]
![image](https://user-images.githubusercontent.com/1611537/31390613-ae78ded4-add4-11e7-9065-819e4b3af0bd.png)

Too much info to read if you're already accustomed with what buildings do (same probably for units). Also breaks mobile by stretching the TR if class `.table-responsive` is on the div outside of the table tag.

Either need a toggle somewhere to show and hide the help texts, or move them to some hover or modal area.

**Comment by straube** [comment]
@WaveHack do you think something like this would be OK?

![screen shot 2017-10-14 at 09 04 29](https://user-images.githubusercontent.com/958870/31575500-e8afbbc6-b0be-11e7-827f-37bfc6d694d0.png)

To show the actual help message, we may use the elements title attribute. The message will show up on hover. What do you think?

**Comment by WaveHack** [comment]
I've tried that solution before, but the problem is that title attrs don't show on mobile because of touch events.

Just thinking and brainstorming out loud here, I can see two options working for this.

1) First solution, in the top right part of the Construct Buildings box, a button to toggle help underneath the building rows.

The problem with this, particularly the help text showing under the building (like it is now), is that it breaks mobile view. The build input tags fall out of screen bounds on my screen. Adding the class .table-responsive to the table makes the table very wide, because it doesn't break off that help text anymore and just pushes the td to the width of the help text in it.

2) Second solution would be something like what you have, but with a touch-friendly button and either an in-place modal or otherwise custom tooltip, preferably where I can use HTML in (like jQuery's .tooltip()).

Please let me know what you think. Also if you have other ideas, feel free to share!

**Comment by straube** [comment]
We can use Bootstrap's tooltip. Since the required assets are already available, adding it is pretty straightforward. It shows on mouseover in desktop and on click in touch/mobile devices. I've just tested on mobile Safari and it looks OK. Check this screenshot out:

![img_7751](https://user-images.githubusercontent.com/958870/31577997-fbf6683a-b0ee-11e7-8abd-dc17e96ba00a.PNG)

**Comment by WaveHack** [comment]
Alright cool. I guess just the regular title attr doesn't work. But if this one works then by all means let's go for this one. 😄

**Comment by WaveHack** [comment]
Fixed. Thanks!
